name: "4.0.x alpha release"
on:
  repository_dispatch:
    types: [new_4.0.x_alpha]

permissions:
  contents: write

jobs:
  compute_timestamps:
    runs-on: ubuntu-latest
    steps:
      - name: Compute human-readable release timestamp
        run: echo "PRERELEASE_TIMESTAMP=`date --rfc-3339=seconds`" >> $GITHUB_ENV
      - name: Compute UNIX release timestamp
        run: echo "PRERELEASE_UNIX_TIMESTAMP=`date +%s`" >> $GITHUB_ENV
  release:
    uses: "./.github/workflows/reusable-release-workflow.yml"
    with:
      base_version: ${{ vars.SERVER_40_NEXT_PATCH_VERSION }}
      prerelease: true
      prerelease_kind: "alpha"
      prerelease_identifier: ${{ github.event.client_payload.prerelease_identifier }}
      release_repository: "rabbitmq/server-packages"
      release_title: ${{ github.event.client_payload.release_title }}
      release_description: ${{ github.event.client_payload.release_description }}
      release_tag: --use-unix-timestamp
      publish_to_cloudsmith: false
    secrets: inherit
  retain_latest_n_alphas:
    needs: [release]
    runs-on: ubuntu-latest
    steps:
      - name: Retain only N latest alpha releases
        uses: docker://rabbitmqdevenv/delete-release-action:latest
        with:
          repository: "rabbitmq/server-packages"
          token: ${{ secrets.MK_RELEASE_AUTOMATION_TOKEN }}
          tag-filter: '^alphas'
          keep-last-n: 10
