name: "4.1.x beta release"
on:
  workflow_dispatch:
    inputs:
      base_version:
        description: "Base version (e.g. 4.1.0) used at build time"
        required: true
        default: "4.1.0"
      preview_version:
        description: "Preview version (e.g. beta) used at build time"
        required: true
        default: "beta"

jobs:
  source_tarball:
    runs-on: ubuntu-latest
    container:
      image: rabbitmqdevenv/build-env-26.2
    steps:
      - name: Clone rabbitmq/rabbitmq-server
        uses: actions/checkout@v4
        with:
          repository: rabbitmq/rabbitmq-server
          ref: main
          path: rabbitmq-server
      - name: Clone rabbitmq/server-packages
        uses: actions/checkout@v4
        with:
          repository: rabbitmq/server-packages
          ref: main
          path: server-packages
      - name: Generate source tarball
        run: |
          cd rabbitmq-server
          gmake source-dist PROJECT_VERSION=${{ github.event.inputs.base_version }}-${{ github.event.inputs.preview_version }}.1
      - name: Store source tarball
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.inputs.base_version }}-${{ github.event.inputs.preview_version }}-source-tarball.zip
          path: "rabbitmq-server/PACKAGES/*"
          retention-days: 2
  generic_binary_package:
    needs: source_tarball
    runs-on: ubuntu-latest
    container:
      image: rabbitmqdevenv/build-env-26.2
    steps:
      - name: Fetch source tarball
        uses: actions/download-artifact@v4
        with:
          name: ${{ github.event.inputs.base_version }}-${{ github.event.inputs.preview_version }}-source-tarball.zip
          path: ./artifacts
      - uses: montudor/action-zip@v1
        with:
          args: unzip ./artifacts/${{ github.event.inputs.base_version }}-${{ github.event.inputs.preview_version }}-source-tarball.zip -d ./artifacts
      - name: Build generic binary package
        run: |
          ls -lha ./artifacts
          gmake SOURCE_DIST_FILE=./artifacts/${{ github.event.inputs.base_version }}-${{ github.event.inputs.preview_version }}.1.tar.xz PROJECT_VERSION=${{ github.event.inputs.base_version }}-${{ github.event.inputs.preview_version }}.1
