name: "4.1.x alpha release"
on:
  repository_dispatch:
    types: [new_4.1.x_alpha]

permissions:
  contents: write

jobs:
  release:
    uses: "./.github/workflows/reusable-release-workflow.yml"
    with:
      base_version: ${{ vars.SERVER_41_NEXT_PATCH_VERSION }}
      prerelease: true
      prerelease_kind: "alpha"
      prerelease_identifier: ${{ github.event.client_payload.prerelease_identifier }}
      release_repository: "rabbitmq/server-packages"
      release_title: ${{ github.event.client_payload.release_title }}
      release_description: ${{ github.event.client_payload.release_description }}
      release_timestamp: ${{ github.event.client_payload.release_timestamp }}
      release_unix_timestamp: ${{ github.event.client_payload.release_unix_timestamp }}
      release_tag: "prerelease.41x.alphas.${{ github.event.client_payload.release_unix_timestamp }}.${{ github.event.client_payload.prerelease_identifier }}"
    secrets: inherit
  retain_latest_n_alphas:
    needs: [release]
    runs-on: ubuntu-latest
    steps:
      - name: Retain only N latest alpha releases
        uses: docker://rabbitmqdevenv/delete-release-action:latest
        with:
          repository: "rabbitmq/server-packages"
          token: ${{ secrets.MK_RELEASE_AUTOMATION_TOKEN }}
          tag-filter: '^prerelease'
          keep-last-n: 10
