name: "4.1.x release candidate"
on:
  workflow_dispatch:
    inputs:
      prerelease_identifier:
        # can be a number, a commit SHA prefix
        type: string
        description: "Preview identifier (an integer) to use"
        required: true
        default: "1"

permissions:
  contents: write

jobs:
  release:
    uses: ./.github/workflows/reusable-release-workflow.yml
    with:
      base_version: "4.1.0"
      prerelease: true
      prerelease_kind: "rc"
      prerelease_identifier: ${{ inputs.prerelease_identifier }}
    secrets: inherit
