name: "4.1.x alpha release"
on:
  repository_dispatch:
    types: [new_4.1.x_alpha]

permissions:
  contents: write

RELEASE_REPOSITORY: "rabbitmq/server-packages"

jobs:
  release:
    uses: "./.github/workflows/reusable-release-workflow.yml"
    with:
      base_version: "4.1.0"
      prerelease: true
      prerelease_kind: "alpha"
      prerelease_identifier: ${{ github.event.client_payload.prerelease_identifier }}
      release_repository: ${{ env.RELEASE_REPOSITORY }}
      release_title: ${{ github.event.client_payload.release_title }}
      release_description: ${{ github.event.client_payload.release_description }}
    secrets: inherit
