name: "4.1.x alpha release"
on:
  repository_dispatch:
    types: [new_4.1.x_alpha]

permissions: write-all

jobs:
  release:
    uses: "./.github/workflows/reusable-release-workflow.yml"
    with:
      base_version: "4.1.0"
      prerelease: true
      prerelease_kind: "alpha"
      prerelease_identifier: ${{ github.event.client_payload.prerelease_identifier }}
    secrets: inherit
