name: "4.1.x release"
on:
  workflow_dispatch:
    inputs:

permissions:
  contents: write

jobs:
  release:
    uses: ./.github/workflows/reusable-release-workflow.yml
    with:
      series_branch: "main"
      # see https://github.com/rabbitmq/build-env-images
      build_env_image: "rabbitmqdevenv/build-env-27.1"
      latest_build_env_image: "rabbitmqdevenv/build-env-27.1"
      base_version: ${{ vars.SERVER_41_NEXT_PATCH_VERSION }}
      prerelease: false
      # Note: this may be intentionally overriden for periods of time for testing
      release_repository: "rabbitmq/server-packages"
      release_title: "RabbitMQ ${{ vars.SERVER_41_NEXT_PATCH_VERSION }}"
      release_description: "RabbitMQ ${{ vars.SERVER_41_NEXT_PATCH_VERSION }}"
      release_tag: "v${{ vars.SERVER_41_NEXT_PATCH_VERSION }}"
      # applies to Debian and RPM packages only
      gpg_sign_release: true
      publish_to_cloudsmith: true
      # Note: this may be intentionally overriden for periods of time for testing
      cloudsmith_repository: "rabbitmq-server-prereleases"
    secrets: inherit
