name: "4.1.x alpha release"
on:
  repository_dispatch:
    types: [new_4.1.x_alpha]
  workflow_dispatch:
    inputs:
      prerelease_identifier:
        # can be a number, a commit SHA prefix
        type: string
        description: "Preview identifier (e.g. an integer or a commit SHA) to use"
        required: true
        default: "1"

permissions:
  contents: write

jobs:
  print_timestamp:
    runs-on: ubuntu-latest
    steps:
      - name: Get current UNIX timestamp
        id: compute_unix_timestamp
        uses: release-kit/unix-timestamp@v1
      - name: Print timestamp
        run: echo '${{ steps.compute_unix_timestamp.outputs.timestamp }}'
  release:
    uses: "./.github/workflows/reusable-release-workflow.yml"
    with:
      series_branch: "main"
      # see https://github.com/rabbitmq/build-env-images
      build_env_image: "rabbitmqdevenv/build-env-27.1"
      base_version: ${{ vars.SERVER_41_NEXT_PATCH_VERSION }}
      prerelease: true
      prerelease_kind: "alpha"
      prerelease_identifier: ${{ inputs.prerelease_identifier || github.event.client_payload.prerelease_identifier }}
      release_repository: "rabbitmq/server-packages"
      release_title: ${{ github.event.client_payload.release_title }}
      release_description: ${{ github.event.client_payload.release_description }}
      release_tag: "(ignored for alphas)"
      # applies to Debian and RPM packages only
      gpg_sign_release: true
      publish_to_cloudsmith: false
    secrets: inherit
  retain_latest_n_alphas:
    needs: [release]
    runs-on: ubuntu-latest
    steps:
      - name: Retain only N latest alpha releases
        uses: docker://rabbitmqdevenv/delete-release-action:latest
        with:
          repository: "rabbitmq/server-packages"
          token: ${{ secrets.MK_RELEASE_AUTOMATION_TOKEN }}
          name-filter: '.*4.1.[0-9]+-alpha.*'
          keep-last-n: 5
  trigger_jepsen_tests:
    needs: [release]
    uses: "./.github/workflows/reusable-trigger-jepsen-tests-workflow.yml"
    with:
      full_version: ${{ needs.release.outputs.full_version }}
      tag_name: ${{ needs.release.outputs.tag_name }}
    secrets: inherit
