name: "Reusable workflow to trigger Jepsen tests"
on:
  workflow_call:
    inputs:
      full_version:
        type: string
        description: The release version (e.g. 4.1.0-alpha.3e509c9f)
        required: true
      tag_name:
        type: string
        description: The release tag name (e.g. alphas.1731626175221)
        required: true

env:
  GITHUB_TOKEN: ${{ secrets.MK_RELEASE_AUTOMATION_TOKEN }}

jobs:
  trigger_jepsen_tests:
    runs-on: ubuntu-24.04
    steps:
      - name: Get version and tag
        run: |
          rabbitmq_binary_url="https://github.com/rabbitmq/server-packages/releases/download/${{ inputs.tag_name }}/rabbitmq-server-generic-unix-${{ inputs.full_version }}.tar.xz"
          MAJOR=$(echo ${{ inputs.full_version }} | cut -f1 -d'.')
          MINOR=$(echo ${{ inputs.full_version }} | cut -f2 -d'.')
          BRANCH=$MAJOR$MINOR
          echo "rabbitmq_branch=$BRANCH"
          echo "rabbitmq_branch=$BRANCH" >> $GITHUB_ENV
          echo "rabbitmq_binary_url=$rabbitmq_binary_url"
          echo "rabbitmq_binary_url=$rabbitmq_binary_url" >> $GITHUB_ENV
      - name: Dispatch event to trigger Jepsen tests
        uses: peter-evans/repository-dispatch@v3
        with:
          event-type: new_alpha_${{ env.rabbitmq_branch }}
          repository: rabbitmq/jepsen
          token: ${{ env.GITHUB_TOKEN }}
          client-payload: >-
            {"binary_url": "${{ env.rabbitmq_binary_url }}"}
